{
 "title": "Dicoding Username - Student Performance Monitoring",
 "tags": [
  "mlflow",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ml_requests_total" }
   ]
  },
  {
   "title": "Prediction Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "ml_prediction_errors_total" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage_ratio * 100" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_memory_usage_ratio * 100"
    }
   ]
  },
  {
   "title": "Mean Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(ml_request_latency_seconds_sum[30s]) / rate(ml_request_latency_seconds_count[30s])",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "Student Final Score predictions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "ml_predicted_score_mean", "legendFormat": "Mean Score" },
    { "expr": "ml_predicted_score_latest", "legendFormat": "Latest Score" },
    { "expr": "ml_predicted_score_max", "legendFormat": "Max Score" },
    { "expr": "ml_predicted_score_min", "legendFormat": "Min Score" }
   ]
  },
  {
   "title": "Mean Study Hours Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ml_input_study_hours_mean", "legendFormat": "Mean Study Hours" }
   ]
  },
  {
   "title": "Mean Attendance Rate Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    { "expr": "ml_input_attendance_rate_mean", "legendFormat": "Mean Attendance" }
   ]
  },
  {
   "title": "Mean Previous Score Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    { "expr": "ml_input_previous_score_mean", "legendFormat": "Mean Previous Score" }
   ]
  }
 ]
}